"""Add OrderCodeLookup table

Revision ID: 6f4530f31d8a
Revises: abb41021d4e4
Create Date: 2025-08-31 00:46:32.209115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f4530f31d8a'
down_revision: Union[str, Sequence[str], None] = 'abb41021d4e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_code_lookup',
    sa.Column('order_code', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('order_code')
    )
    op.create_index(op.f('ix_order_code_lookup_order_code'), 'order_code_lookup', ['order_code'], unique=False)
    op.create_index(op.f('ix_order_code_lookup_order_id'), 'order_code_lookup', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_code_lookup_order_id'), table_name='order_code_lookup')
    op.drop_index(op.f('ix_order_code_lookup_order_code'), table_name='order_code_lookup')
    op.drop_table('order_code_lookup')
    # ### end Alembic commands ###
