"""Add model_type to AIModel

Revision ID: 8a2017c378d5
Revises: f5abacd1a158
Create Date: 2025-09-05 07:25:01.023988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a2017c378d5'
down_revision: Union[str, Sequence[str], None] = 'f5abacd1a158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_models', sa.Column('model_type', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_ai_models_model_type'), 'ai_models', ['model_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_models_model_type'), table_name='ai_models')
    op.drop_column('ai_models', 'model_type')
    # ### end Alembic commands ###
