"""remove_unique_on_product_vector

Revision ID: 95368d46bc8d
Revises: c02c21bc7c99
Create Date: 2025-09-05 11:17:30.816895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95368d46bc8d'
down_revision: Union[str, Sequence[str], None] = 'c02c21bc7c99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_vectors_product_id'), table_name='product_vectors')
    op.create_index(op.f('ix_product_vectors_product_id'), 'product_vectors', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_vectors_product_id'), table_name='product_vectors')
    op.create_index(op.f('ix_product_vectors_product_id'), 'product_vectors', ['product_id'], unique=True)
    # ### end Alembic commands ###
