"""add create_time for product vector

Revision ID: afdcd696b6c4
Revises: 95368d46bc8d
Create Date: 2025-09-07 07:21:27.809238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afdcd696b6c4'
down_revision: Union[str, Sequence[str], None] = '95368d46bc8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_vectors', sa.Column('image_id', sa.Uuid(), nullable=True))
    op.add_column('product_vectors', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_product_vectors_image_id'), 'product_vectors', ['image_id'], unique=False)
    op.create_foreign_key(None, 'product_vectors', 'product_images', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_vectors', type_='foreignkey')
    op.drop_index(op.f('ix_product_vectors_image_id'), table_name='product_vectors')
    op.drop_column('product_vectors', 'created_at')
    op.drop_column('product_vectors', 'image_id')
    # ### end Alembic commands ###
