"""add_product_vector_table

Revision ID: c02c21bc7c99
Revises: 8a2017c378d5
Create Date: 2025-09-05 11:00:17.298147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c02c21bc7c99'
down_revision: Union[str, Sequence[str], None] = '8a2017c378d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_vectors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ai_models.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_vectors_model_id'), 'product_vectors', ['model_id'], unique=False)
    op.create_index(op.f('ix_product_vectors_product_id'), 'product_vectors', ['product_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_vectors_product_id'), table_name='product_vectors')
    op.drop_index(op.f('ix_product_vectors_model_id'), table_name='product_vectors')
    op.drop_table('product_vectors')
    # ### end Alembic commands ###
