"""Link QR token to shopping session

Revision ID: ff349cfc1bef
Revises: 6f4530f31d8a
Create Date: 2025-08-31 02:30:05.471905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff349cfc1bef'
down_revision: Union[str, Sequence[str], None] = '6f4530f31d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qr_auth_tokens', sa.Column('shopping_session_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'qr_auth_tokens', 'shopping_sessions', ['shopping_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'qr_auth_tokens', type_='foreignkey')
    op.drop_column('qr_auth_tokens', 'shopping_session_id')
    # ### end Alembic commands ###
